# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    form_invoice_type:
        class: AppBundle\Form\Type\InvoiceType
    form_client_type:
        class: AppBundle\Form\Type\ClientType
    form_item_type:
        class: AppBundle\Form\Type\ItemType
    form_profile_type:
        class: AppBundle\Form\Type\ProfileType
    voicein.twig.currency:
        class: AppBundle\Twig\Currency
        tags:
            - { name: twig.extension}
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }