<?php

namespace AppBundle\Entity;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getClientsOptions()
    {
        $user = $this->container->get('security.content')->getToken()->getUser();
        $clientIds = $profileIds = array();
        $clients = $this->getDoctrine()
            ->getRepository('App:Client')
            ->findBy(array(
                'user' => $user
            ));
        foreach ($clients as $client) {
            array_push($clientIds, $client);
        }
        $queryClients = $this->getEntityManager()
            ->createQueryBuilder('i')
            ->andWhere('i.client IN (:ids)')
            ->setParameter('ids', $clientIds);

        return $queryClients;
    }

    public function getProfilesOptions()
    {
        $user = $this->container->get('security.content')->getToken()->getUser();
        $profiles = $this->getDoctrine()
            ->getRepository('App:Profile')
            ->findBy(array(
                'user' => $user
            ));
        foreach ($profiles as $profile) {
            array_push($profileIds, $profile);
        }
        $queryProfiles = $this->getEntityManager()
            ->createQueryBuilder('i')
            ->andWhere('i.profile IN (:ids)')
            ->setParameter('ids', $profileIds);

        return $queryProfiles;
    }
}
